[package]
name = "rdenticon"
authors = ["jay3332"]
version = "0.1.4"
edition = "2021"
description = "An implementation of jdenticon in pure Rust."
repository = "https://github.com/jay3332/rdenticon"
readme = "README.md"
license = "MIT"

[dependencies]
sha1_smol = "1"

[dependencies.ril]
git = "https://github.com/jay3332/ril"
branch = "main"
version = ">= 0.9, < 0.11"
default-features = false

[features]
default = ["ril/png"]

[dev-dependencies]
criterion = "0.4"
rand = "0.8"

[[bench]]
name = "benchmarks"
path = "benches/benchmarks.rs"
harness = false
